### ISSUE TITLE
Oxidized Copper doesn't work.

### ISSUE THREAD

**Issue by Antstone2898** [Boombabob/Its-All-Connected#1]
The reason is that the folder is named in correctly. It is called "oxidised" when it should be called "oxidized"
![image_2023-11-22_185741849](https://github.com/Boombabob/Its-All-Connected/assets/147186856/f7dbe472-049c-4091-a58d-705e2cd47cbb)
![Screenshot 2023-11-22 185644](https://github.com/Boombabob/Its-All-Connected/assets/147186856/088da2ee-30c8-4212-abff-4748f0aaa5b1)

**Comment by james-reynolds1** [comment]
Sorry, I have been meaning to get around to fixing all the bugs with this texture pack. Thanks for letting me know!

I will have some more time over the summer break (I'm in the southern hemisphere), so I am aiming to polish this pack and fix all the bugs in the next month or so.

**Comment by james-reynolds1** [comment]
just released an update fixing everything 👍
